eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/

server:
  port: 8101

spring:
  application:
    name: accountremoteservice
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    suffix: .html

feign:
  hystrix:
    enabled: true