eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/

server:
  port: 8102

spring:
  application:
    name: accountremoteservice
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    suffix: .html
  zipkin:
    base-url: http://localhost:9411

feign:
  hystrix:
    enabled: true